name: family_food_analysis
description: "A cross-platform Flutter application for Family Food & Grocery Analysis, Nutrition tracking, BMI-based meal suggestions, and Google Sheets synchronization."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.2.3
  google_mlkit_commons: ^0.13.0
  google_mlkit_text_recognition: ^0.17.1
  google_mlkit_image_labeling: ^0.16.1
  file_picker: ^8.1.2
  pdfx: ^2.11.0
  receive_sharing_intent: ^1.9.0
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
